html_page1 = '''
 <head>
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
  <meta http-equiv="Content-Style-Type" content="text/css" />
  <meta name="generator" content="Aspose.Words for .NET 15.1.0.0" />
  <title></title>
 </head>
 <body>
  <div>
   <div style="text-align:center">
    <table cellspacing="0" cellpadding="0" style="border-collapse:collapse; margin:0 auto; width:521.9pt">
     <tbody>
      <tr style="height:20.25pt">
       <td colspan="10" style="padding-left:5.4pt; padding-right:5.4pt; vertical-align:middle; width:511.1pt"><p style="line-height:16pt; margin:0pt; text-align:center"><span style="font-family:宋体; font-size:16pt; font-weight:bold">居民死亡医学证明（推断）书</span></p></td>
      </tr>
      <tr style="height:24.75pt">
       <td colspan="10" style="border-bottom-color:#000000; border-bottom-style:solid; border-bottom-width:0.75pt; padding-left:5.4pt; padding-right:5.4pt; vertical-align:middle; width:511.1pt"><p style="line-height:13pt; margin:0pt"><span style="font-family:宋体; font-size:9pt">{0}</span><br /><span style="font-family:宋体; font-size:9pt">行政区划代码</span><span style="font-family:宋体; font-size:14pt"> </span><span style="font-family:宋体; font-size:14pt"> </span><span style="font-family:宋体; font-size:10pt">{1}</span><span style="font-family:宋体; font-size:10pt"> </span><span style="font-family:宋体; font-size:14pt"> </span><span style="font-family:宋体; font-size:9pt"> 编号：</span><span style="font-family:宋体; font-size:14pt"> </span><span style="font-family:宋体; font-size:9pt">{2}</span></p></td>
      </tr>
      <tr style="height:26.1pt">
       <td style="border-bottom-color:#000000; border-bottom-style:solid; border-bottom-width:0.75pt; border-left-color:#000000; border-left-style:solid; border-left-width:0.75pt; border-right-color:#000000; border-right-style:solid; border-right-width:0.75pt; padding-left:5.03pt; padding-right:5.03pt; vertical-align:middle; width:48.2pt"><p style="line-height:12pt; margin:0pt; text-align:center"><span style="font-family:宋体; font-size:9pt">死者姓名</span></p></td>
       <td colspan="2" style="border-bottom-color:#000000; border-bottom-style:solid; border-bottom-width:0.75pt; border-right-color:#000000; border-right-style:solid; border-right-width:0.75pt; border-top-color:#000000; border-top-style:solid; border-top-width:0.75pt; padding-left:5.4pt; padding-right:5.03pt; vertical-align:middle; width:94.45pt"><p style="line-height:12pt; margin:0pt; text-align:center"><span style="font-family:宋体; font-size:9pt">{3}</span></p></td>
       <td style="border-bottom-color:#000000; border-bottom-style:solid; border-bottom-width:0.75pt; border-right-color:#000000; border-right-style:solid; border-right-width:0.75pt; padding-left:5.4pt; padding-right:5.03pt; vertical-align:middle; width:27.2pt"><p style="line-height:12pt; margin:0pt; text-align:center"><span style="font-family:宋体; font-size:9pt">性别</span></p></td>
       <td colspan="2" style="border-bottom-color:#000000; border-bottom-style:solid; border-bottom-width:0.75pt; border-right-color:#000000; border-right-style:solid; border-right-width:0.75pt; border-top-color:#000000; border-top-style:solid; border-top-width:0.75pt; padding-left:5.4pt; padding-right:5.03pt; vertical-align:middle; width:78.2pt"><p style="line-height:12pt; margin:0pt"><span style="font-family:宋体; font-size:9pt">{4}</span></p></td>
       <td style="border-bottom-color:#000000; border-bottom-style:solid; border-bottom-width:0.75pt; border-right-color:#000000; border-right-style:solid; border-right-width:0.75pt; padding-left:5.4pt; padding-right:5.03pt; vertical-align:middle; width:29.2pt"><p style="line-height:12pt; margin:0pt; text-align:center"><span style="font-family:宋体; font-size:9pt">民族</span></p></td>
       <td style="border-bottom-color:#000000; border-bottom-style:solid; border-bottom-width:0.75pt; border-right-color:#000000; border-right-style:solid; border-right-width:0.75pt; padding-left:5.4pt; padding-right:5.03pt; vertical-align:middle; width:48.45pt"><p style="line-height:12pt; margin:0pt"><span style="font-family:宋体; font-size:9pt">{5}</span></p></td>
       <td style="border-bottom-color:#000000; border-bottom-style:solid; border-bottom-width:0.75pt; border-right-color:#000000; border-right-style:solid; border-right-width:0.75pt; padding-left:5.4pt; padding-right:5.03pt; vertical-align:middle; width:33.2pt"><p style="line-height:12pt; margin:0pt; text-align:center"><span style="font-family:宋体; font-size:9pt">国家或</span><br /><span style="font-family:宋体; font-size:9pt">地区</span></p></td>
       <td style="border-bottom-color:#000000; border-bottom-style:solid; border-bottom-width:0.75pt; border-right-color:#000000; border-right-style:solid; border-right-width:0.75pt; padding-left:5.4pt; padding-right:5.03pt; vertical-align:middle; width:76.6pt"><p style="line-height:12pt; margin:0pt"><span style="font-family:宋体; font-size:9pt">中国</span></p></td>
      </tr>
      <tr style="height:42.75pt">
       <td style="border-left-color:#000000; border-left-style:solid; border-left-width:0.75pt; padding-left:5.03pt; padding-right:5.4pt; vertical-align:middle; width:48.2pt"><p style="line-height:12pt; margin:0pt; text-align:center"><span style="font-family:宋体; font-size:9pt">有效身份</span><br /><span style="font-family:宋体; font-size:9pt">证件类别</span></p></td>
       <td colspan="2" style="border-bottom-color:#000000; border-bottom-style:solid; border-bottom-width:0.75pt; border-left-color:#000000; border-left-style:solid; border-left-width:0.75pt; border-right-color:#000000; border-right-style:solid; border-right-width:0.75pt; border-top-color:#000000; border-top-style:solid; border-top-width:0.75pt; padding-left:5.03pt; padding-right:5.03pt; vertical-align:middle; width:94.45pt"><p style="line-height:12pt; margin:0pt"><span style="font-family:宋体; font-size:9pt">{6}</span></p></td>
       <td style="border-bottom-color:#000000; border-bottom-style:solid; border-bottom-width:0.75pt; border-right-color:#000000; border-right-style:solid; border-right-width:0.75pt; padding-left:5.4pt; padding-right:5.03pt; vertical-align:middle; width:27.2pt"><p style="line-height:12pt; margin:0pt; text-align:center"><span style="font-family:宋体; font-size:9pt">证件</span><br /><span style="font-family:宋体; font-size:9pt">号码</span></p></td>
       <td colspan="2" style="border-bottom-color:#000000; border-bottom-style:solid; border-bottom-width:0.75pt; border-right-color:#000000; border-right-style:solid; border-right-width:0.75pt; border-top-color:#000000; border-top-style:solid; border-top-width:0.75pt; padding-left:5.4pt; padding-right:5.03pt; vertical-align:middle; width:78.2pt"><p style="line-height:12pt; margin:0pt; text-align:center"><span style="font-family:宋体; font-size:9pt">{7}</span></td>
       <td style="border-bottom-color:#000000; border-bottom-style:solid; border-bottom-width:0.75pt; border-right-color:#000000; border-right-style:solid; border-right-width:0.75pt; padding-left:5.4pt; padding-right:5.03pt; vertical-align:middle; width:29.2pt"><p style="line-height:12pt; margin:0pt; text-align:center"><span style="font-family:宋体; font-size:9pt">年龄</span></p></td>
       <td style="padding-left:5.4pt; padding-right:5.4pt; vertical-align:middle; width:48.45pt"><p style="line-height:12pt; margin:0pt"><span style="font-family:宋体; font-size:9pt">{8}</span></p></td>
       <td style="border-bottom-color:#000000; border-bottom-style:solid; border-bottom-width:0.75pt; border-left-color:#000000; border-left-style:solid; border-left-width:0.75pt; border-right-color:#000000; border-right-style:solid; border-right-width:0.75pt; padding-left:5.03pt; padding-right:5.03pt; vertical-align:middle; width:33.2pt"><p style="line-height:12pt; margin:0pt; text-align:center"><span style="font-family:宋体; font-size:9pt">婚姻</span><br /><span style="font-family:宋体; font-size:9pt">状况</span></p></td>
       <td style="border-bottom-color:#000000; border-bottom-style:solid; border-bottom-width:0.75pt; border-right-color:#000000; border-right-style:solid; border-right-width:0.75pt; padding-left:5.4pt; padding-right:5.03pt; vertical-align:middle; width:76.6pt"><p style="line-height:12pt; margin:0pt"><span style="font-family:宋体; font-size:9pt">{9}</span></p></td>
      </tr>
      <tr style="height:46.5pt">
       <td style="border-bottom-color:#000000; border-bottom-style:solid; border-bottom-width:0.75pt; border-left-color:#000000; border-left-style:solid; border-left-width:0.75pt; border-right-color:#000000; border-right-style:solid; border-right-width:0.75pt; border-top-color:#000000; border-top-style:solid; border-top-width:0.75pt; padding-left:5.03pt; padding-right:5.03pt; vertical-align:middle; width:48.2pt"><p style="line-height:12pt; margin:0pt; text-align:center"><span style="font-family:宋体; font-size:9pt">出生</span><br /><span style="font-family:宋体; font-size:9pt">日期</span></p></td>
       <td colspan="2" style="border-bottom-color:#000000; border-bottom-style:solid; border-bottom-width:0.75pt; border-right-color:#000000; border-right-style:solid; border-right-width:0.75pt; border-top-color:#000000; border-top-style:solid; border-top-width:0.75pt; padding-left:5.4pt; padding-right:5.03pt; vertical-align:middle; width:94.45pt"><p style="line-height:12pt; margin:0pt; text-align:center"><span style="font-family:宋体; font-size:9pt">{10}</span><span style="font-family:宋体; font-size:9pt"> </span></p></td>
       <td style="border-bottom-color:#000000; border-bottom-style:solid; border-bottom-width:0.75pt; border-right-color:#000000; border-right-style:solid; border-right-width:0.75pt; padding-left:5.4pt; padding-right:5.03pt; vertical-align:middle; width:27.2pt"><p style="line-height:12pt; margin:0pt; text-align:center"><span style="font-family:宋体; font-size:9pt">文化</span><br /><span style="font-family:宋体; font-size:9pt">程度</span></p></td>
       <td colspan="2" style="border-bottom-color:#000000; border-bottom-style:solid; border-bottom-width:0.75pt; border-right-color:#000000; border-right-style:solid; border-right-width:0.75pt; border-top-color:#000000; border-top-style:solid; border-top-width:0.75pt; padding-left:5.4pt; padding-right:5.03pt; vertical-align:middle; width:78.2pt"><p style="line-height:12pt; margin:0pt"><span style="font-family:宋体; font-size:9pt">{11}</span></p></td>
       <td style="border-bottom-color:#000000; border-bottom-style:solid; border-bottom-width:0.75pt; border-right-color:#000000; border-right-style:solid; border-right-width:0.75pt; padding-left:5.4pt; padding-right:5.03pt; vertical-align:middle; width:29.2pt"><p style="line-height:12pt; margin:0pt; text-align:center"><span style="font-family:宋体; font-size:9pt">个人</span><br /><span style="font-family:宋体; font-size:9pt">身份</span></p></td>
   <td colspan="3" style="border-bottom-color:#000000; border-bottom-style:solid; border-bottom-width:0.75pt; border-right-color:#000000; border-right-style:solid; border-right-width:0.75pt; border-top-color:#000000; border-top-style:solid; border-top-width:0.75pt; padding-left:5.4pt; padding-right:5.03pt; vertical-align:middle; width:179.85pt"><p style="line-height:12pt; margin:0pt"><span style="font-family:宋体; font-size:9pt">{12}</span></p></td>
      </tr>
      <tr style="height:26.1pt">
       <td style="border-bottom-color:#000000; border-bottom-style:solid; border-bottom-width:0.75pt; border-left-color:#000000; border-left-style:solid; border-left-width:0.75pt; border-right-color:#000000; border-right-style:solid; border-right-width:0.75pt; padding-left:5.03pt; padding-right:5.03pt; vertical-align:middle; width:48.2pt"><p style="line-height:12pt; margin:0pt; text-align:center"><span style="font-family:宋体; font-size:9pt">死亡日期</span></p></td>
       <td colspan="2" style="border-bottom-color:#000000; border-bottom-style:solid; border-bottom-width:0.75pt; border-right-color:#000000; border-right-style:solid; border-right-width:0.75pt; border-top-color:#000000; border-top-style:solid; border-top-width:0.75pt; padding-left:5.4pt; padding-right:5.03pt; vertical-align:middle; width:94.45pt"><p style="line-height:12pt; margin:0pt; text-align:center"><span style="font-family:宋体; font-size:9pt"> </span><span style="font-family:宋体; font-size:9pt">{13}</span></p></td>
       <td style="border-bottom-color:#000000; border-bottom-style:solid; border-bottom-width:0.75pt; border-right-color:#000000; border-right-style:solid; border-right-width:0.75pt; padding-left:5.4pt; padding-right:5.03pt; vertical-align:middle; width:27.2pt"><p style="line-height:12pt; margin:0pt; text-align:center"><span style="font-family:宋体; font-size:9pt">死亡</span><br /><span style="font-family:宋体; font-size:9pt">地点</span></p></td>
       <td colspan="3" style="border-bottom-color:#000000; border-bottom-style:solid; border-bottom-width:0.75pt; border-right-color:#000000; border-right-style:solid; border-right-width:0.75pt; border-top-color:#000000; border-top-style:solid; border-top-width:0.75pt; padding-left:5.4pt; padding-right:5.03pt; vertical-align:middle; width:118.2pt"><p style="line-height:12pt; margin:0pt"><span style="font-family:宋体; font-size:9pt">{14}</span></p></td>
       <td colspan="2" style="border-bottom-color:#000000; border-bottom-style:solid; border-bottom-width:0.75pt; border-right-color:#000000; border-right-style:solid; border-right-width:0.75pt; border-top-color:#000000; border-top-style:solid; border-top-width:0.75pt; padding-left:5.4pt; padding-right:5.03pt; vertical-align:middle; width:92.45pt"><p style="line-height:12pt; margin:0pt; text-align:center"><span style="font-family:宋体; font-size:9pt">死亡时是否处于妊娠期</span><br /><span style="font-family:宋体; font-size:9pt">或妊娠终止后42天内</span></p></td>
       <td style="border-bottom-color:#000000; border-bottom-style:solid; border-bottom-width:0.75pt; border-right-color:#000000; border-right-style:solid; border-right-width:0.75pt; padding-left:5.4pt; padding-right:5.03pt; vertical-align:middle; width:76.6pt"><p style="line-height:12pt; margin:0pt; text-align:center"><span style="font-family:宋体; font-size:9pt">{15}</span></p></td>
      </tr>
      <tr style="height:26.1pt">
       <td style="border-bottom-color:#000000; border-bottom-style:solid; border-bottom-width:0.75pt; border-left-color:#000000; border-left-style:solid; border-left-width:0.75pt; border-right-color:#000000; border-right-style:solid; border-right-width:0.75pt; padding-left:5.03pt; padding-right:5.03pt; vertical-align:middle; width:48.2pt"><p style="line-height:12pt; margin:0pt; text-align:center"><span style="font-family:宋体; font-size:9pt">生前</span><br /><span style="font-family:宋体; font-size:9pt">工作单位</span></p></td>
       <td colspan="2" style="border-bottom-color:#000000; border-bottom-style:solid; border-bottom-width:0.75pt; border-right-color:#000000; border-right-style:solid; border-right-width:0.75pt; border-top-color:#000000; border-top-style:solid; border-top-width:0.75pt; padding-left:5.4pt; padding-right:5.03pt; vertical-align:middle; width:94.45pt"><p style="line-height:12pt; margin:0pt; text-align:center"><span style="font-family:宋体; font-size:9pt">{16}</span></p></td>
       <td style="border-bottom-color:#000000; border-bottom-style:solid; border-bottom-width:0.75pt; border-right-color:#000000; border-right-style:solid; border-right-width:0.75pt; padding-left:5.4pt; padding-right:5.03pt; vertical-align:middle; width:27.2pt"><p style="line-height:12pt; margin:0pt; text-align:center"><span style="font-family:宋体; font-size:9pt">户籍</span><br /><span style="font-family:宋体; font-size:9pt">地址</span></p></td>
       <td colspan="3" style="border-bottom-color:#000000; border-bottom-style:solid; border-bottom-width:0.75pt; border-right-color:#000000; border-right-style:solid; border-right-width:0.75pt; border-top-color:#000000; border-top-style:solid; border-top-width:0.75pt; padding-left:5.4pt; padding-right:5.03pt; vertical-align:middle; width:118.2pt"><p style="line-height:12pt; margin:0pt; text-align:center"><span style="font-family:宋体; font-size:9pt">{17}</span></p></td>
       <td style="border-bottom-color:#000000; border-bottom-style:solid; border-bottom-width:0.75pt; border-right-color:#000000; border-right-style:solid; border-right-width:0.75pt; padding-left:5.4pt; padding-right:5.03pt; vertical-align:middle; width:48.45pt"><p style="line-height:12pt; margin:0pt; text-align:center"><span style="font-family:宋体; font-size:9pt">常住</span><br /><span style="font-family:宋体; font-size:9pt">地址</span></p></td>
       <td colspan="2" style="border-bottom-color:#000000; border-bottom-style:solid; border-bottom-width:0.75pt; border-right-color:#000000; border-right-style:solid; border-right-width:0.75pt; border-top-color:#000000; border-top-style:solid; border-top-width:0.75pt; padding-left:5.4pt; padding-right:5.03pt; vertical-align:middle; width:120.6pt"><p style="line-height:12pt; margin:0pt; text-align:center"><span style="font-family:宋体; font-size:9pt">{18}</span></p></td>
      </tr>
      <tr style="height:26.1pt">
       <td style="border-bottom-color:#000000; border-bottom-style:solid; border-bottom-width:0.75pt; border-left-color:#000000; border-left-style:solid; border-left-width:0.75pt; border-right-color:#000000; border-right-style:solid; border-right-width:0.75pt; padding-left:5.03pt; padding-right:5.03pt; vertical-align:middle; width:48.2pt"><p style="line-height:12pt; margin:0pt; text-align:center"><span style="font-family:宋体; font-size:9pt">可联系的</span><br /><span style="font-family:宋体; font-size:9pt">家属姓名</span></p></td>
       <td colspan="2" style="border-bottom-color:#000000; border-bottom-style:solid; border-bottom-width:0.75pt; border-right-color:#000000; border-right-style:solid; border-right-width:0.75pt; border-top-color:#000000; border-top-style:solid; border-top-width:0.75pt; padding-left:5.4pt; padding-right:5.03pt; vertical-align:middle; width:94.45pt"><p style="line-height:12pt; margin:0pt; text-align:center"><span style="font-family:宋体; font-size:9pt">{19}</span></p></td>
       <td style="border-bottom-color:#000000; border-bottom-style:solid; border-bottom-width:0.75pt; border-right-color:#000000; border-right-style:solid; border-right-width:0.75pt; padding-left:5.4pt; padding-right:5.03pt; vertical-align:middle; width:27.2pt"><p style="line-height:12pt; margin:0pt; text-align:center"><span style="font-family:宋体; font-size:9pt">联系</span><br /><span style="font-family:宋体; font-size:9pt">电话</span></p></td>
       <td colspan="3" style="border-bottom-color:#000000; border-bottom-style:solid; border-bottom-width:0.75pt; border-right-color:#000000; border-right-style:solid; border-right-width:0.75pt; border-top-color:#000000; border-top-style:solid; border-top-width:0.75pt; padding-left:5.4pt; padding-right:5.03pt; vertical-align:middle; width:118.2pt"><p style="line-height:12pt; margin:0pt; text-align:center"><span style="font-family:宋体; font-size:9pt">{20}</span></p></td>
       <td style="border-bottom-color:#000000; border-bottom-style:solid; border-bottom-width:0.75pt; border-right-color:#000000; border-right-style:solid; border-right-width:0.75pt; padding-left:5.4pt; padding-right:5.03pt; vertical-align:middle; width:48.45pt"><p style="line-height:12pt; margin:0pt; text-align:center"><span style="font-family:宋体; font-size:9pt">家属住址</span><br /><span style="font-family:宋体; font-size:9pt">或工作单位</span></p></td>
       <td colspan="2" style="border-bottom-color:#000000; border-bottom-style:solid; border-bottom-width:0.75pt; border-right-color:#000000; border-right-style:solid; border-right-width:0.75pt; border-top-color:#000000; border-top-style:solid; border-top-width:0.75pt; padding-left:5.4pt; padding-right:5.03pt; vertical-align:middle; width:120.6pt"><p style="line-height:12pt; margin:0pt; text-align:center"><span style="font-family:宋体; font-size:9pt">{21}</span></p></td>
      </tr>
      <tr style="height:26.1pt">
       <td colspan="3" style="border-bottom-color:#000000; border-bottom-style:solid; border-bottom-width:0.75pt; border-left-color:#000000; border-left-style:solid; border-left-width:0.75pt; border-right-color:#000000; border-right-style:solid; border-right-width:0.75pt; border-top-color:#000000; border-top-style:solid; border-top-width:0.75pt; padding-left:5.03pt; padding-right:5.03pt; vertical-align:middle; width:153.45pt"><p style="line-height:12pt; margin:0pt"><span style="font-family:宋体; font-size:9pt"> 致死的主要疾病诊断</span></p></td>
       <td colspan="5" style="border-bottom-color:#000000; border-bottom-style:solid; border-bottom-width:0.75pt; border-right-color:#000000; border-right-style:solid; border-right-width:0.75pt; border-top-color:#000000; border-top-style:solid; border-top-width:0.75pt; padding-left:5.4pt; padding-right:5.03pt; vertical-align:middle; width:215.45pt"><p style="line-height:12pt; margin:0pt; text-align:center"><span style="font-family:宋体; font-size:9pt">疾病名称（</span><span style="font-family:宋体; font-size:9pt">勿填症状</span><span style="font-family:宋体; font-size:9pt">体征）</span></p></td>
       <td colspan="2" style="border-bottom-color:#000000; border-bottom-style:solid; border-bottom-width:0.75pt; border-right-color:#000000; border-right-style:solid; border-right-width:0.75pt; border-top-color:#000000; border-top-style:solid; border-top-width:0.75pt; padding-left:5.4pt; padding-right:5.03pt; vertical-align:middle; width:120.6pt"><p style="line-height:12pt; margin:0pt; text-align:center"><span style="font-family:宋体; font-size:9pt">发病至死亡大概间隔时间</span></p></td>
      </tr>
      <tr style="height:26.1pt">
       <td colspan="3" style="border-bottom-color:#000000; border-bottom-style:solid; border-bottom-width:0.75pt; border-left-color:#000000; border-left-style:solid; border-left-width:0.75pt; border-right-color:#000000; border-right-style:solid; border-right-width:0.75pt; border-top-color:#000000; border-top-style:solid; border-top-width:0.75pt; padding-left:5.03pt; padding-right:5.03pt; vertical-align:middle; width:153.45pt"><p style="line-height:12pt; margin:0pt"><span style="font-family:宋体; font-size:9pt"> </span><span style="font-family:宋体; font-size:9pt">I.</span><span style="font-family:宋体; font-size:9pt">(a)直接死亡原因</span></p></td>
       <td colspan="5" style="border-bottom-color:#000000; border-bottom-style:solid; border-bottom-width:0.75pt; border-right-color:#000000; border-right-style:solid; border-right-width:0.75pt; border-top-color:#000000; border-top-style:solid; border-top-width:0.75pt; padding-left:5.4pt; padding-right:5.03pt; vertical-align:middle; width:215.45pt"><p style="line-height:12pt; margin:0pt"><span style="font-family:宋体; font-size:9pt">{22}</span></p></td>
       <td colspan="2" style="border-bottom-color:#000000; border-bottom-style:solid; border-bottom-width:0.75pt; border-right-color:#000000; border-right-style:solid; border-right-width:0.75pt; border-top-color:#000000; border-top-style:solid; border-top-width:0.75pt; padding-left:5.4pt; padding-right:5.03pt; vertical-align:middle; width:120.6pt"><p style="line-height:12pt; margin:0pt; text-align:center"><span style="font-family:宋体; font-size:9pt">{23}</span></p></td>
      </tr>
      <tr style="height:26.1pt">
       <td colspan="3" style="border-bottom-color:#000000; border-bottom-style:solid; border-bottom-width:0.75pt; border-left-color:#000000; border-left-style:solid; border-left-width:0.75pt; border-right-color:#000000; border-right-style:solid; border-right-width:0.75pt; border-top-color:#000000; border-top-style:solid; border-top-width:0.75pt; padding-left:5.03pt; padding-right:5.03pt; vertical-align:middle; width:153.45pt"><p style="line-height:12pt; margin:0pt"><span style="font-family:宋体; font-size:9pt"> (b)引起(a)的疾病或情况</span></p></td>
       <td colspan="5" style="border-bottom-color:#000000; border-bottom-style:solid; border-bottom-width:0.75pt; border-right-color:#000000; border-right-style:solid; border-right-width:0.75pt; border-top-color:#000000; border-top-style:solid; border-top-width:0.75pt; padding-left:5.4pt; padding-right:5.03pt; vertical-align:middle; width:215.45pt"><p style="line-height:12pt; margin:0pt"><span style="font-family:宋体; font-size:9pt">{24}</span></p></td>
       <td colspan="2" style="border-bottom-color:#000000; border-bottom-style:solid; border-bottom-width:0.75pt; border-right-color:#000000; border-right-style:solid; border-right-width:0.75pt; border-top-color:#000000; border-top-style:solid; border-top-width:0.75pt; padding-left:5.4pt; padding-right:5.03pt; vertical-align:middle; width:120.6pt"><p style="line-height:12pt; margin:0pt; text-align:center"><span style="font-family:宋体; font-size:9pt">{25}</span></p></td>
      </tr>
      <tr style="height:26.1pt">
       <td colspan="3" style="border-bottom-color:#000000; border-bottom-style:solid; border-bottom-width:0.75pt; border-left-color:#000000; border-left-style:solid; border-left-width:0.75pt; border-right-color:#000000; border-right-style:solid; border-right-width:0.75pt; border-top-color:#000000; border-top-style:solid; border-top-width:0.75pt; padding-left:5.03pt; padding-right:5.03pt; vertical-align:middle; width:153.45pt"><p style="line-height:12pt; margin:0pt"><span style="font-family:宋体; font-size:9pt"> (c)引起(b)的疾病或情况</span></p></td>
       <td colspan="5" style="border-bottom-color:#000000; border-bottom-style:solid; border-bottom-width:0.75pt; border-right-color:#000000; border-right-style:solid; border-right-width:0.75pt; border-top-color:#000000; border-top-style:solid; border-top-width:0.75pt; padding-left:5.4pt; padding-right:5.03pt; vertical-align:middle; width:215.45pt"><p style="line-height:12pt; margin:0pt"><span style="font-family:宋体; font-size:9pt">{26}</span></p></td>
       <td colspan="2" style="border-bottom-color:#000000; border-bottom-style:solid; border-bottom-width:0.75pt; border-right-color:#000000; border-right-style:solid; border-right-width:0.75pt; border-top-color:#000000; border-top-style:solid; border-top-width:0.75pt; padding-left:5.4pt; padding-right:5.03pt; vertical-align:middle; width:120.6pt"><p style="line-height:12pt; margin:0pt; text-align:center"><span style="font-family:宋体; font-size:9pt">{27}</span></p></td>
      </tr>
      <tr style="height:26.1pt">
       <td colspan="3" style="border-bottom-color:#000000; border-bottom-style:solid; border-bottom-width:0.75pt; border-left-color:#000000; border-left-style:solid; border-left-width:0.75pt; border-right-color:#000000; border-right-style:solid; border-right-width:0.75pt; border-top-color:#000000; border-top-style:solid; border-top-width:0.75pt; padding-left:5.03pt; padding-right:5.03pt; vertical-align:middle; width:153.45pt"><p style="line-height:12pt; margin:0pt"><span style="font-family:宋体; font-size:9pt"> (d)引起(c)的疾病或情况</span></p></td>
       <td colspan="5" style="border-bottom-color:#000000; border-bottom-style:solid; border-bottom-width:0.75pt; border-right-color:#000000; border-right-style:solid; border-right-width:0.75pt; border-top-color:#000000; border-top-style:solid; border-top-width:0.75pt; padding-left:5.4pt; padding-right:5.03pt; vertical-align:middle; width:215.45pt"><p style="line-height:12pt; margin:0pt"><span style="font-family:宋体; font-size:9pt">{28}</span></p></td>
       <td colspan="2" style="border-bottom-color:#000000; border-bottom-style:solid; border-bottom-width:0.75pt; border-right-color:#000000; border-right-style:solid; border-right-width:0.75pt; border-top-color:#000000; border-top-style:solid; border-top-width:0.75pt; padding-left:5.4pt; padding-right:5.03pt; vertical-align:middle; width:120.6pt"><p style="line-height:12pt; margin:0pt; text-align:center"><span style="font-family:宋体; font-size:9pt">{29}</span></p></td>
      </tr>
      <tr style="height:28.5pt">
       <td colspan="3" style="border-bottom-color:#000000; border-bottom-style:solid; border-bottom-width:0.75pt; border-left-color:#000000; border-left-style:solid; border-left-width:0.75pt; border-right-color:#000000; border-right-style:solid; border-right-width:0.75pt; border-top-color:#000000; border-top-style:solid; border-top-width:0.75pt; padding-left:5.03pt; padding-right:5.03pt; vertical-align:middle; width:153.45pt"><p style="line-height:12pt; margin:0pt"><span style="font-family:宋体; font-size:9pt"> II.其他疾病诊断（促进死亡，但与</span><br /><span style="font-family:宋体; font-size:9pt"> 导致死亡无关的其他重要情况）</span></p></td>
       <td colspan="5" style="border-bottom-color:#000000; border-bottom-style:solid; border-bottom-width:0.75pt; border-right-color:#000000; border-right-style:solid; border-right-width:0.75pt; border-top-color:#000000; border-top-style:solid; border-top-width:0.75pt; padding-left:5.4pt; padding-right:5.03pt; vertical-align:middle; width:215.45pt"><p style="line-height:12pt; margin:0pt"><span style="font-family:宋体; font-size:9pt">{30}</span></p></td>
       <td colspan="2" style="border-bottom-color:#000000; border-bottom-style:solid; border-bottom-width:0.75pt; border-left-color:#000000; border-left-style:solid; border-left-width:0.75pt; border-right-color:#000000; border-right-style:solid; border-right-width:0.75pt; border-top-color:#000000; border-top-style:solid; border-top-width:0.75pt; padding-left:5.03pt; padding-right:5.03pt; vertical-align:middle; width:120.6pt"><p style="line-height:12pt; margin:0pt; text-align:center"><span style="font-family:宋体; font-size:9pt">{31}</span></p></td>
      </tr>
      <tr style="height:27.95pt">
       <td style="border-bottom-color:#000000; border-bottom-style:solid; border-bottom-width:0.75pt; border-left-color:#000000; border-left-style:solid; border-left-width:0.75pt; border-right-color:#000000; border-right-style:solid; border-right-width:0.75pt; padding-left:5.03pt; padding-right:5.03pt; vertical-align:middle; width:48.2pt"><p style="line-height:12pt; margin:0pt; text-align:center"><span style="font-family:宋体; font-size:7.5pt">生前主要疾病</span><br /><span style="font-family:宋体; font-size:7.5pt">最高诊断单位</span></p></td>
       <td colspan="6" style="border-bottom-color:#000000; border-bottom-style:solid; border-bottom-width:0.75pt; border-right-color:#000000; border-right-style:solid; border-right-width:0.75pt; border-top-color:#000000; border-top-style:solid; border-top-width:0.75pt; padding-left:5.4pt; padding-right:5.03pt; vertical-align:middle; width:261.45pt"><p style="line-height:12pt; margin:0pt"><span style="font-family:宋体; font-size:9pt">{32}</span></p></td>
       <td style="border-bottom-color:#000000; border-bottom-style:solid; border-bottom-width:0.75pt; padding-left:5.4pt; padding-right:5.4pt; vertical-align:middle; width:48.45pt"><p style="line-height:12pt; margin:0pt; text-align:center"><span style="font-family:宋体; font-size:7.5pt">生前主要疾病</span><br /><span style="font-family:宋体; font-size:7.5pt">最高诊断依据</span></p></td>
       <td colspan="2" style="border-bottom-color:#000000; border-bottom-style:solid; border-bottom-width:0.75pt; border-left-color:#000000; border-left-style:solid; border-left-width:0.75pt; border-right-color:#000000; border-right-style:solid; border-right-width:0.75pt; border-top-color:#000000; border-top-style:solid; border-top-width:0.75pt; padding-left:5.03pt; padding-right:5.03pt; vertical-align:middle; width:120.6pt"><p style="line-height:12pt; margin:0pt"><span style="font-family:宋体; font-size:9pt">{33}</span></p></td>
      </tr>
      <tr style="height:28.5pt">
       <td style="border-left-color:#000000; border-left-style:solid; border-left-width:0.75pt; border-right-color:#000000; border-right-style:solid; border-right-width:0.75pt; padding-left:5.03pt; padding-right:5.03pt; vertical-align:middle; width:48.2pt"><p style="line-height:12pt; margin:0pt; text-align:center"><span style="font-family:宋体; font-size:9pt">医师签名</span></p></td>
       <td colspan="2" style="border-right-color:#000000; border-right-style:solid; border-right-width:0.75pt; border-top-color:#000000; border-top-style:solid; border-top-width:0.75pt; padding-left:5.4pt; padding-right:5.03pt; vertical-align:middle; width:94.45pt"><p style="line-height:12pt; margin:0pt; text-align:center"><span style="font-family:宋体; font-size:9pt">张三丰</span></p></td>
       <td colspan="4" style="border-left-color:#000000; border-left-style:solid; border-left-width:0.75pt; border-top-color:#000000; border-top-style:solid; border-top-width:0.75pt; padding-left:5.03pt; padding-right:5.4pt; vertical-align:middle; width:156.2pt"><p style="line-height:12pt; margin:0pt"><span style="font-family:宋体; font-size:9pt"> 医疗卫生</span><br /><span style="font-family:宋体; font-size:9pt"> 机构盖章</span></p></td>
       <td style="border-left-color:#000000; border-left-style:solid; border-left-width:0.75pt; border-right-color:#000000; border-right-style:solid; border-right-width:0.75pt; border-top-color:#000000; border-top-style:solid; border-top-width:0.75pt; padding-left:5.03pt; padding-right:5.03pt; vertical-align:middle; width:48.45pt"><p style="line-height:12pt; margin:0pt"><span style="font-family:宋体; font-size:9pt"> 填表日期：</span></p></td>
       <td colspan="2" style="border-left-color:#000000; border-left-style:solid; border-left-width:0.75pt; border-right-color:#000000; border-right-style:solid; border-right-width:0.75pt; border-top-color:#000000; border-top-style:solid; border-top-width:0.75pt; padding-left:5.03pt; padding-right:5.03pt; vertical-align:middle; width:120.6pt"><p style="line-height:12pt; margin:0pt 0pt 0pt 17.1pt; orphans:0; widows:0"><span style="font-family:宋体; font-size:9pt">张三丰</span></p></td>
      </tr>
      <tr style="height:28.5pt">
       <td colspan="3" style="border-bottom-color:#000000; border-bottom-style:solid; border-bottom-width:0.75pt; border-left-color:#000000; border-left-style:solid; border-left-width:0.75pt; border-right-color:#000000; border-right-style:solid; border-right-width:0.75pt; border-top-color:#000000; border-top-style:solid; border-top-width:0.75pt; padding-left:5.03pt; padding-right:5.03pt; vertical-align:middle; width:153.45pt"><p style="line-height:14pt; margin:0pt"><span style="font-family:宋体; font-size:9pt"> (以下由编码人员填写) 根本死亡原因:</span></p></td>
       <td colspan="4" style="border-bottom-color:#000000; border-bottom-style:solid; border-bottom-width:0.75pt; border-left-color:#000000; border-left-style:solid; border-left-width:0.75pt; border-right-color:#000000; border-right-style:solid; border-right-width:0.75pt; border-top-color:#000000; border-top-style:solid; border-top-width:0.75pt; padding-left:5.03pt; padding-right:5.03pt; vertical-align:middle; width:156.2pt"><p style="line-height:14pt; margin:0pt; orphans:0; widows:0"><span style="font-family:宋体; font-size:9pt">{34}</span></p></td>
       <td style="border-bottom-color:#000000; border-bottom-style:solid; border-bottom-width:0.75pt; border-right-color:#000000; border-right-style:solid; border-right-width:0.75pt; border-top-color:#000000; border-top-style:solid; border-top-width:0.75pt; padding-left:5.4pt; padding-right:5.03pt; vertical-align:middle; width:48.45pt"><p style="line-height:14pt; margin:0pt"><span style="font-family:宋体; font-size:9pt"> ICD编码：</span></p></td>
       <td colspan="2" style="border-bottom-color:#000000; border-bottom-style:solid; border-bottom-width:0.75pt; border-left-color:#000000; border-left-style:solid; border-left-width:0.75pt; border-right-color:#000000; border-right-style:solid; border-right-width:0.75pt; border-top-color:#000000; border-top-style:solid; border-top-width:0.75pt; padding-left:5.03pt; padding-right:5.03pt; vertical-align:middle; width:120.6pt"><p style="line-height:14pt; margin:0pt"><span style="font-family:宋体; font-size:9pt">{35}</span></p></td>
      </tr>
      <tr style="height:23.25pt">
       <td colspan="10" style="border-bottom-color:#000000; border-bottom-style:solid; border-bottom-width:0.75pt; padding-left:5.4pt; padding-right:5.4pt; vertical-align:bottom; width:511.1pt"><p style="line-height:14pt; margin:0pt; text-align:center"><span style="font-family:宋体; font-size:15pt; font-weight:bold"> </span><span style="font-family:宋体; font-size:15pt; font-weight:bold">死亡调查记录</span></p></td>
      </tr>
      <tr style="height:15.6pt">
       <td colspan="10" rowspan="6" style="border-bottom-color:#000000; border-bottom-style:solid; border-bottom-width:0.75pt; border-left-color:#000000; border-left-style:solid; border-left-width:0.75pt; border-right-color:#000000; border-right-style:solid; border-right-width:0.75pt; border-top-color:#000000; border-top-style:solid; border-top-width:0.75pt; padding-left:5.03pt; padding-right:5.03pt; vertical-align:top; width:511.1pt"><p style="line-height:11pt; margin:0pt"><span style="font-family:宋体; font-size:9pt">张三丰</span></p></td>
      </tr>
      <tr style="height:15.6pt">
       <td style="border:none; height:15.6pt; width:0pt"></td>
      </tr>
      <tr style="height:15.6pt">
       <td style="border:none; height:15.6pt; width:0pt"></td>
      </tr>
      <tr style="height:15.6pt">
       <td style="border:none; height:15.6pt; width:0pt"></td>
      </tr>
      <tr style="height:15.6pt">
       <td style="border:none; height:15.6pt; width:0pt"></td>
      </tr>
      <tr style="height:11pt">
       <td style="border:none; height:11pt; width:0pt"></td>
      </tr>
      <tr style="height:26.1pt">
       <td style="border-bottom-color:#000000; border-bottom-style:solid; border-bottom-width:0.75pt; border-left-color:#000000; border-left-style:solid; border-left-width:0.75pt; border-right-color:#000000; border-right-style:solid; border-right-width:0.75pt; padding-left:5.03pt; padding-right:5.03pt; vertical-align:middle; width:48.2pt"><p style="line-height:11pt; margin:0pt; text-align:center"><span style="font-family:宋体; font-size:9pt">被调查者</span><br /><span style="font-family:宋体; font-size:9pt">姓 名</span></p></td>
       <td style="border-bottom-color:#000000; border-bottom-style:solid; border-bottom-width:0.75pt; padding-left:5.4pt; padding-right:5.4pt; vertical-align:middle; width:53.2pt"><p style="line-height:11pt; margin:0pt"><span style="font-family:宋体; font-size:9pt">张三丰</span></p></td>
       <td style="border-bottom-color:#000000; border-bottom-style:solid; border-bottom-width:0.75pt; border-left-color:#000000; border-left-style:solid; border-left-width:0.75pt; border-right-color:#000000; border-right-style:solid; border-right-width:0.75pt; padding-left:5.03pt; padding-right:5.03pt; vertical-align:middle; width:30.45pt"><p style="line-height:11pt; margin:0pt; text-align:center"><span style="font-family:宋体; font-size:9pt">与死者</span><br /><span style="font-family:宋体; font-size:9pt">关 系</span></p></td>
       <td style="border-bottom-color:#000000; border-bottom-style:solid; border-bottom-width:0.75pt; border-right-color:#000000; border-right-style:solid; border-right-width:0.75pt; padding-left:5.4pt; padding-right:5.03pt; vertical-align:middle; width:27.2pt"><p style="line-height:11pt; margin:0pt"><span style="font-family:宋体; font-size:9pt">张三丰</span></p></td>
       <td style="border-bottom-color:#000000; border-bottom-style:solid; border-bottom-width:0.75pt; border-right-color:#000000; border-right-style:solid; border-right-width:0.75pt; padding-left:5.4pt; padding-right:5.03pt; vertical-align:middle; width:47.2pt"><p style="line-height:11pt; margin:0pt; text-align:center"><span style="font-family:宋体; font-size:9pt">联系</span><br /><span style="font-family:宋体; font-size:9pt">电话</span></p></td>
       <td colspan="2" style="border-bottom-color:#000000; border-bottom-style:solid; border-bottom-width:0.75pt; border-right-color:#000000; border-right-style:solid; border-right-width:0.75pt; border-top-color:#000000; border-top-style:solid; border-top-width:0.75pt; padding-left:5.4pt; padding-right:5.03pt; vertical-align:middle; width:60.2pt"><p style="line-height:11pt; margin:0pt; text-align:center"><span style="font-family:宋体; font-size:9pt">张三丰</span></p></td>
       <td style="border-bottom-color:#000000; border-bottom-style:solid; border-bottom-width:0.75pt; border-right-color:#000000; border-right-style:solid; border-right-width:0.75pt; padding-left:5.4pt; padding-right:5.03pt; vertical-align:middle; width:48.45pt"><p style="line-height:11pt; margin:0pt; text-align:center"><span style="font-family:宋体; font-size:9pt">联系地址</span><br /><span style="font-family:宋体; font-size:9pt">或工作单位</span></p></td>
       <td colspan="2" style="border-bottom-color:#000000; border-bottom-style:solid; border-bottom-width:0.75pt; border-right-color:#000000; border-right-style:solid; border-right-width:0.75pt; border-top-color:#000000; border-top-style:solid; border-top-width:0.75pt; padding-left:5.4pt; padding-right:5.03pt; vertical-align:middle; width:120.6pt"><p style="line-height:11pt; margin:0pt; text-align:center"><span style="font-family:宋体; font-size:9pt">张三丰</span></p></td>
      </tr>
      <tr style="height:14.9pt">
       <td style="border-bottom-color:#000000; border-bottom-style:solid; border-bottom-width:0.75pt; border-left-color:#000000; border-left-style:solid; border-left-width:0.75pt; border-right-color:#000000; border-right-style:solid; border-right-width:0.75pt; padding-left:5.03pt; padding-right:5.03pt; vertical-align:middle; width:48.2pt"><p style="line-height:11pt; margin:0pt; text-align:center"><span style="font-family:宋体; font-size:9pt">死因推断</span></p></td>
       <td colspan="3" style="border-bottom-color:#000000; border-bottom-style:solid; border-bottom-width:0.75pt; border-right-color:#000000; border-right-style:solid; border-right-width:0.75pt; border-top-color:#000000; border-top-style:solid; border-top-width:0.75pt; padding-left:5.4pt; padding-right:5.03pt; vertical-align:middle; width:132.45pt"><p style="line-height:11pt; margin:0pt; text-align:center"><span style="font-family:宋体; font-size:9pt">张三丰</span></p></td>
       <td style="border-bottom-color:#000000; border-bottom-style:solid; border-bottom-width:0.75pt; border-right-color:#000000; border-right-style:solid; border-right-width:0.75pt; padding-left:5.4pt; padding-right:5.03pt; vertical-align:middle; width:47.2pt"><p style="line-height:11pt; margin:0pt; text-align:center"><span style="font-family:宋体; font-size:9pt">调查者签名</span></p></td>
       <td colspan="2" style="border-bottom-color:#000000; border-bottom-style:solid; border-bottom-width:0.75pt; border-top-color:#000000; border-top-style:solid; border-top-width:0.75pt; padding-left:5.4pt; padding-right:5.4pt; vertical-align:middle; width:60.2pt"><p style="line-height:11pt; margin:0pt; text-align:center"><span style="font-family:宋体; font-size:9pt">张三丰</span></p></td>
       <td style="border-bottom-color:#000000; border-bottom-style:solid; border-bottom-width:0.75pt; border-left-color:#000000; border-left-style:solid; border-left-width:0.75pt; border-right-color:#000000; border-right-style:solid; border-right-width:0.75pt; padding-left:5.03pt; padding-right:5.03pt; vertical-align:middle; width:48.45pt"><p style="line-height:11pt; margin:0pt; text-align:center"><span style="font-family:宋体; font-size:9pt">调查日期</span></p></td>
       <td colspan="2" style="border-bottom-color:#000000; border-bottom-style:solid; border-bottom-width:0.75pt; border-right-color:#000000; border-right-style:solid; border-right-width:0.75pt; border-top-color:#000000; border-top-style:solid; border-top-width:0.75pt; padding-left:5.4pt; padding-right:5.03pt; vertical-align:middle; width:120.6pt"><p style="line-height:11pt; margin:0pt; text-align:center"><span style="font-family:宋体; font-size:9pt">张三丰</span><span style="font-family:宋体; font-size:9pt"> </span></p></td>
      </tr>
      <tr style="height:25.5pt">
       <td colspan="10" style="border-top-color:#000000; border-top-style:solid; border-top-width:0.75pt; padding-left:5.4pt; padding-right:5.4pt; vertical-align:middle; width:511.1pt"><p style="line-height:11pt; margin:0pt"><span style="font-family:宋体; font-size:8.5pt"> 注：①此表填写范围为在家、养老服务机构、其他场所正常死亡者；②被调查者应为死者近亲或知情人；③调查时应出具以下资料：被调查者有效身份证件，居住地居委会或村委会证明，死者身份证和/或户口簿、生前病史卡.</span></p></td>
      </tr>
     </tbody>
    </table>
 </body>
'''

test_page = '''
<html>
 <head>
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
  <meta http-equiv="Content-Style-Type" content="text/css" />
  <meta name="generator" content="Aspose.Words for .NET 15.1.0.0" />
  <title></title>
 </head>
 <body>
  <div>
   <div style="text-align:center">
    <table cellspacing="0" cellpadding="0" style="border-collapse:collapse; margin:0 auto; width:521.9pt">
     <tbody>
      <tr style="height:18.75pt">
       <td colspan="11" style="padding-left:5.4pt; padding-right:5.4pt; vertical-align:middle; width:511.1pt"><p style="line-height:16pt; margin:0pt; text-align:center"><span style="font-family:宋体; font-size:16pt; font-weight:bold">居民死亡医学证明（推断）书</span></p></td>
      </tr>
      <tr style="height:14.2pt">
       <td colspan="11" style="padding-left:5.4pt; padding-right:5.4pt; vertical-align:middle; width:511.1pt"><p style="line-height:16pt; margin:0pt; orphans:0; widows:0"><span style="font-family:宋体; font-size:9pt; font-weight:normal">安徽省黄山市黄山区</span></p></td>
      </tr>
      <tr style="height:23.9pt">
       <td colspan="5" style="border-bottom-color:#000000; border-bottom-style:solid; border-bottom-width:0.75pt; padding-left:5.4pt; padding-right:5.4pt; vertical-align:middle; width:244.95pt"><p style="line-height:13pt; margin:0pt"><span style="font-family:宋体; font-size:9pt">行政区划代码</span><span style="font-family:宋体; font-size:14pt"> </span><span style="font-family:宋体; font-size:10pt">341003</span><span style="font-family:宋体; font-size:10pt">00</span></p></td>
       <td colspan="6" style="border-bottom-color:#000000; border-bottom-style:solid; border-bottom-width:0.75pt; padding-left:5.4pt; padding-right:5.4pt; vertical-align:middle; width:255.35pt"><p style="line-height:13pt; margin:0pt; orphans:0; widows:0"><span style="font-family:宋体; font-size:9pt">编号：</span><span style="font-family:宋体; font-size:14pt"> </span><span style="font-family:宋体; font-size:9pt">123456789</span></p></td>
      </tr>
      <tr style="height:26.1pt">
       <td style="border-bottom-color:#000000; border-bottom-style:solid; border-bottom-width:0.75pt; border-left-color:#000000; border-left-style:solid; border-left-width:0.75pt; border-right-color:#000000; border-right-style:solid; border-right-width:0.75pt; padding-left:5.03pt; padding-right:5.03pt; vertical-align:middle; width:48.2pt"><p style="line-height:12pt; margin:0pt; text-align:center"><span style="font-family:宋体; font-size:9pt">死者姓名</span></p></td>
       <td colspan="2" style="border-bottom-color:#000000; border-bottom-style:solid; border-bottom-width:0.75pt; border-right-color:#000000; border-right-style:solid; border-right-width:0.75pt; border-top-color:#000000; border-top-style:solid; border-top-width:0.75pt; padding-left:5.4pt; padding-right:5.03pt; vertical-align:middle; width:94.45pt"><p style="line-height:12pt; margin:0pt; text-align:center"><span style="font-family:宋体; font-size:9pt">张三丰</span></p></td>
       <td style="border-bottom-color:#000000; border-bottom-style:solid; border-bottom-width:0.75pt; border-right-color:#000000; border-right-style:solid; border-right-width:0.75pt; padding-left:5.4pt; padding-right:5.03pt; vertical-align:middle; width:27.2pt"><p style="line-height:12pt; margin:0pt; text-align:center"><span style="font-family:宋体; font-size:9pt">性别</span></p></td>
       <td colspan="3" style="border-bottom-color:#000000; border-bottom-style:solid; border-bottom-width:0.75pt; border-right-color:#000000; border-right-style:solid; border-right-width:0.75pt; border-top-color:#000000; border-top-style:solid; border-top-width:0.75pt; padding-left:5.4pt; padding-right:5.03pt; vertical-align:middle; width:78.2pt"><p style="line-height:12pt; margin:0pt; text-align:center"><span style="font-family:宋体; font-size:9pt">张三丰</span></p></td>
       <td style="border-bottom-color:#000000; border-bottom-style:solid; border-bottom-width:0.75pt; border-right-color:#000000; border-right-style:solid; border-right-width:0.75pt; padding-left:5.4pt; padding-right:5.03pt; vertical-align:middle; width:29.2pt"><p style="line-height:12pt; margin:0pt; text-align:center"><span style="font-family:宋体; font-size:9pt">民族</span></p></td>
       <td style="border-bottom-color:#000000; border-bottom-style:solid; border-bottom-width:0.75pt; border-right-color:#000000; border-right-style:solid; border-right-width:0.75pt; padding-left:5.4pt; padding-right:5.03pt; vertical-align:middle; width:48.45pt"><p style="line-height:12pt; margin:0pt; text-align:center"><span style="font-family:宋体; font-size:9pt">张三丰</span></p></td>
       <td style="border-bottom-color:#000000; border-bottom-style:solid; border-bottom-width:0.75pt; border-right-color:#000000; border-right-style:solid; border-right-width:0.75pt; padding-left:5.4pt; padding-right:5.03pt; vertical-align:middle; width:33.2pt"><p style="line-height:12pt; margin:0pt; text-align:center"><span style="font-family:宋体; font-size:9pt">国家或</span><br /><span style="font-family:宋体; font-size:9pt">地区</span></p></td>
       <td style="border-bottom-color:#000000; border-bottom-style:solid; border-bottom-width:0.75pt; border-right-color:#000000; border-right-style:solid; border-right-width:0.75pt; padding-left:5.4pt; padding-right:5.03pt; vertical-align:middle; width:76.6pt"><p style="line-height:12pt; margin:0pt; text-align:center"><span style="font-family:宋体; font-size:9pt">张三丰</span></p></td>
      </tr>
      <tr style="height:51pt">
       <td style="border-left-color:#000000; border-left-style:solid; border-left-width:0.75pt; padding-left:5.03pt; padding-right:5.4pt; vertical-align:middle; width:48.2pt"><p style="line-height:12pt; margin:0pt; text-align:center"><span style="font-family:宋体; font-size:9pt">有效身份</span><br /><span style="font-family:宋体; font-size:9pt">证件类别</span></p></td>
       <td colspan="2" style="border-bottom-color:#000000; border-bottom-style:solid; border-bottom-width:0.75pt; border-left-color:#000000; border-left-style:solid; border-left-width:0.75pt; border-right-color:#000000; border-right-style:solid; border-right-width:0.75pt; border-top-color:#000000; border-top-style:solid; border-top-width:0.75pt; padding-left:5.03pt; padding-right:5.03pt; vertical-align:middle; width:94.45pt"><p style="line-height:12pt; margin:0pt; text-align:center"><span style="font-family:宋体; font-size:9pt">张三丰</span></p></td>
       <td style="border-bottom-color:#000000; border-bottom-style:solid; border-bottom-width:0.75pt; border-right-color:#000000; border-right-style:solid; border-right-width:0.75pt; padding-left:5.4pt; padding-right:5.03pt; vertical-align:middle; width:27.2pt"><p style="line-height:12pt; margin:0pt; text-align:center"><span style="font-family:宋体; font-size:9pt">证件</span><br /><span style="font-family:宋体; font-size:9pt">号码</span></p></td>
       <td colspan="3" style="border-bottom-color:#000000; border-bottom-style:solid; border-bottom-width:0.75pt; border-right-color:#000000; border-right-style:solid; border-right-width:0.75pt; border-top-color:#000000; border-top-style:solid; border-top-width:0.75pt; padding-left:5.4pt; padding-right:5.03pt; vertical-align:middle; width:78.2pt"><p style="line-height:12pt; margin:0pt; text-align:center"><span style="font-family:宋体; font-size:9pt">张三丰</span></p></td>
       <td style="border-bottom-color:#000000; border-bottom-style:solid; border-bottom-width:0.75pt; border-right-color:#000000; border-right-style:solid; border-right-width:0.75pt; padding-left:5.4pt; padding-right:5.03pt; vertical-align:middle; width:29.2pt"><p style="line-height:12pt; margin:0pt; text-align:center"><span style="font-family:宋体; font-size:9pt">年龄</span></p></td>
       <td style="padding-left:5.4pt; padding-right:5.4pt; vertical-align:middle; width:48.45pt"><p style="line-height:12pt; margin:0pt; text-align:center"><span style="font-family:宋体; font-size:9pt">张三丰</span></p></td>
       <td style="border-bottom-color:#000000; border-bottom-style:solid; border-bottom-width:0.75pt; border-left-color:#000000; border-left-style:solid; border-left-width:0.75pt; border-right-color:#000000; border-right-style:solid; border-right-width:0.75pt; padding-left:5.03pt; padding-right:5.03pt; vertical-align:middle; width:33.2pt"><p style="line-height:12pt; margin:0pt; text-align:center"><span style="font-family:宋体; font-size:9pt">婚姻</span><br /><span style="font-family:宋体; font-size:9pt">状况</span></p></td>
       <td style="border-bottom-color:#000000; border-bottom-style:solid; border-bottom-width:0.75pt; border-right-color:#000000; border-right-style:solid; border-right-width:0.75pt; padding-left:5.4pt; padding-right:5.03pt; vertical-align:middle; width:76.6pt"><p style="line-height:12pt; margin:0pt; text-align:center"><span style="font-family:宋体; font-size:9pt">张三丰</span></p></td>
      </tr>
      <tr style="height:46.5pt">
       <td style="border-bottom-color:#000000; border-bottom-style:solid; border-bottom-width:0.75pt; border-left-color:#000000; border-left-style:solid; border-left-width:0.75pt; border-right-color:#000000; border-right-style:solid; border-right-width:0.75pt; border-top-color:#000000; border-top-style:solid; border-top-width:0.75pt; padding-left:5.03pt; padding-right:5.03pt; vertical-align:middle; width:48.2pt"><p style="line-height:12pt; margin:0pt; text-align:center"><span style="font-family:宋体; font-size:9pt">出生</span><br /><span style="font-family:宋体; font-size:9pt">日期</span></p></td>
       <td colspan="2" style="border-bottom-color:#000000; border-bottom-style:solid; border-bottom-width:0.75pt; border-right-color:#000000; border-right-style:solid; border-right-width:0.75pt; border-top-color:#000000; border-top-style:solid; border-top-width:0.75pt; padding-left:5.4pt; padding-right:5.03pt; vertical-align:middle; width:94.45pt"><p style="line-height:12pt; margin:0pt; text-align:center"><span style="font-family:宋体; font-size:9pt">张三丰</span></p></td>
       <td style="border-bottom-color:#000000; border-bottom-style:solid; border-bottom-width:0.75pt; border-right-color:#000000; border-right-style:solid; border-right-width:0.75pt; padding-left:5.4pt; padding-right:5.03pt; vertical-align:middle; width:27.2pt"><p style="line-height:12pt; margin:0pt; text-align:center"><span style="font-family:宋体; font-size:9pt">文化</span><br /><span style="font-family:宋体; font-size:9pt">程度</span></p></td>
       <td colspan="3" style="border-bottom-color:#000000; border-bottom-style:solid; border-bottom-width:0.75pt; border-right-color:#000000; border-right-style:solid; border-right-width:0.75pt; border-top-color:#000000; border-top-style:solid; border-top-width:0.75pt; padding-left:5.4pt; padding-right:5.03pt; vertical-align:middle; width:78.2pt"><p style="line-height:12pt; margin:0pt; text-align:center"><span style="font-family:宋体; font-size:9pt">张三丰</span></p></td>
       <td style="border-bottom-color:#000000; border-bottom-style:solid; border-bottom-width:0.75pt; border-right-color:#000000; border-right-style:solid; border-right-width:0.75pt; padding-left:5.4pt; padding-right:5.03pt; vertical-align:middle; width:29.2pt"><p style="line-height:12pt; margin:0pt; text-align:center"><span style="font-family:宋体; font-size:9pt">个人</span><br /><span style="font-family:宋体; font-size:9pt">身份</span></p></td>
       <td colspan="3" style="border-bottom-color:#000000; border-bottom-style:solid; border-bottom-width:0.75pt; border-right-color:#000000; border-right-style:solid; border-right-width:0.75pt; border-top-color:#000000; border-top-style:solid; border-top-width:0.75pt; padding-left:5.4pt; padding-right:5.03pt; vertical-align:middle; width:179.85pt"><p style="line-height:12pt; margin:0pt; text-align:center"><span style="font-family:宋体; font-size:9pt">张三丰</span></p></td>
      </tr>
      <tr style="height:26.1pt">
       <td style="border-bottom-color:#000000; border-bottom-style:solid; border-bottom-width:0.75pt; border-left-color:#000000; border-left-style:solid; border-left-width:0.75pt; border-right-color:#000000; border-right-style:solid; border-right-width:0.75pt; padding-left:5.03pt; padding-right:5.03pt; vertical-align:middle; width:48.2pt"><p style="line-height:12pt; margin:0pt; text-align:center"><span style="font-family:宋体; font-size:9pt">死亡日期</span></p></td>
       <td colspan="2" style="border-bottom-color:#000000; border-bottom-style:solid; border-bottom-width:0.75pt; border-right-color:#000000; border-right-style:solid; border-right-width:0.75pt; border-top-color:#000000; border-top-style:solid; border-top-width:0.75pt; padding-left:5.4pt; padding-right:5.03pt; vertical-align:middle; width:94.45pt"><p style="line-height:12pt; margin:0pt; text-align:center"><span style="font-family:宋体; font-size:9pt">张三丰</span></p></td>
       <td style="border-bottom-color:#000000; border-bottom-style:solid; border-bottom-width:0.75pt; border-right-color:#000000; border-right-style:solid; border-right-width:0.75pt; padding-left:5.4pt; padding-right:5.03pt; vertical-align:middle; width:27.2pt"><p style="line-height:12pt; margin:0pt; text-align:center"><span style="font-family:宋体; font-size:9pt">死亡</span><br /><span style="font-family:宋体; font-size:9pt">地点</span></p></td>
       <td colspan="4" style="border-bottom-color:#000000; border-bottom-style:solid; border-bottom-width:0.75pt; border-right-color:#000000; border-right-style:solid; border-right-width:0.75pt; border-top-color:#000000; border-top-style:solid; border-top-width:0.75pt; padding-left:5.4pt; padding-right:5.03pt; vertical-align:middle; width:118.2pt"><p style="line-height:12pt; margin:0pt; text-align:center"><span style="font-family:宋体; font-size:9pt">张三丰</span></p></td>
       <td colspan="2" style="border-bottom-color:#000000; border-bottom-style:solid; border-bottom-width:0.75pt; border-right-color:#000000; border-right-style:solid; border-right-width:0.75pt; border-top-color:#000000; border-top-style:solid; border-top-width:0.75pt; padding-left:5.4pt; padding-right:5.03pt; vertical-align:middle; width:92.45pt"><p style="line-height:12pt; margin:0pt; text-align:center"><span style="font-family:宋体; font-size:9pt">死亡时是否处于妊娠期</span><br /><span style="font-family:宋体; font-size:9pt">或妊娠终止后42天内</span></p></td>
       <td style="border-bottom-color:#000000; border-bottom-style:solid; border-bottom-width:0.75pt; border-right-color:#000000; border-right-style:solid; border-right-width:0.75pt; padding-left:5.4pt; padding-right:5.03pt; vertical-align:middle; width:76.6pt"><p style="line-height:12pt; margin:0pt; text-align:center"><span style="font-family:宋体; font-size:9pt">张三丰</span></p></td>
      </tr>
      <tr style="height:26.1pt">
       <td style="border-bottom-color:#000000; border-bottom-style:solid; border-bottom-width:0.75pt; border-left-color:#000000; border-left-style:solid; border-left-width:0.75pt; border-right-color:#000000; border-right-style:solid; border-right-width:0.75pt; padding-left:5.03pt; padding-right:5.03pt; vertical-align:middle; width:48.2pt"><p style="line-height:12pt; margin:0pt; text-align:center"><span style="font-family:宋体; font-size:9pt">生前</span><br /><span style="font-family:宋体; font-size:9pt">工作单位</span></p></td>
       <td colspan="2" style="border-bottom-color:#000000; border-bottom-style:solid; border-bottom-width:0.75pt; border-right-color:#000000; border-right-style:solid; border-right-width:0.75pt; border-top-color:#000000; border-top-style:solid; border-top-width:0.75pt; padding-left:5.4pt; padding-right:5.03pt; vertical-align:middle; width:94.45pt"><p style="line-height:12pt; margin:0pt; text-align:center"><span style="font-family:宋体; font-size:9pt">张三丰</span></p></td>
       <td style="border-bottom-color:#000000; border-bottom-style:solid; border-bottom-width:0.75pt; border-right-color:#000000; border-right-style:solid; border-right-width:0.75pt; padding-left:5.4pt; padding-right:5.03pt; vertical-align:middle; width:27.2pt"><p style="line-height:12pt; margin:0pt; text-align:center"><span style="font-family:宋体; font-size:9pt">户籍</span><br /><span style="font-family:宋体; font-size:9pt">地址</span></p></td>
       <td colspan="4" style="border-bottom-color:#000000; border-bottom-style:solid; border-bottom-width:0.75pt; border-right-color:#000000; border-right-style:solid; border-right-width:0.75pt; border-top-color:#000000; border-top-style:solid; border-top-width:0.75pt; padding-left:5.4pt; padding-right:5.03pt; vertical-align:middle; width:118.2pt"><p style="line-height:12pt; margin:0pt; text-align:center"><span style="font-family:宋体; font-size:9pt">张三丰</span></p></td>
       <td style="border-bottom-color:#000000; border-bottom-style:solid; border-bottom-width:0.75pt; border-right-color:#000000; border-right-style:solid; border-right-width:0.75pt; padding-left:5.4pt; padding-right:5.03pt; vertical-align:middle; width:48.45pt"><p style="line-height:12pt; margin:0pt; text-align:center"><span style="font-family:宋体; font-size:9pt">常住</span><br /><span style="font-family:宋体; font-size:9pt">地址</span></p></td>
       <td colspan="2" style="border-bottom-color:#000000; border-bottom-style:solid; border-bottom-width:0.75pt; border-right-color:#000000; border-right-style:solid; border-right-width:0.75pt; border-top-color:#000000; border-top-style:solid; border-top-width:0.75pt; padding-left:5.4pt; padding-right:5.03pt; vertical-align:middle; width:120.6pt"><p style="line-height:12pt; margin:0pt; text-align:center"><span style="font-family:宋体; font-size:9pt">张三丰</span></p></td>
      </tr>
      <tr style="height:26.1pt">
       <td style="border-bottom-color:#000000; border-bottom-style:solid; border-bottom-width:0.75pt; border-left-color:#000000; border-left-style:solid; border-left-width:0.75pt; border-right-color:#000000; border-right-style:solid; border-right-width:0.75pt; padding-left:5.03pt; padding-right:5.03pt; vertical-align:middle; width:48.2pt"><p style="line-height:12pt; margin:0pt; text-align:center"><span style="font-family:宋体; font-size:9pt">可联系的</span><br /><span style="font-family:宋体; font-size:9pt">家属姓名</span></p></td>
       <td colspan="2" style="border-bottom-color:#000000; border-bottom-style:solid; border-bottom-width:0.75pt; border-right-color:#000000; border-right-style:solid; border-right-width:0.75pt; border-top-color:#000000; border-top-style:solid; border-top-width:0.75pt; padding-left:5.4pt; padding-right:5.03pt; vertical-align:middle; width:94.45pt"><p style="line-height:12pt; margin:0pt; text-align:center"><span style="font-family:宋体; font-size:9pt">张三丰</span></p></td>
       <td style="border-bottom-color:#000000; border-bottom-style:solid; border-bottom-width:0.75pt; border-right-color:#000000; border-right-style:solid; border-right-width:0.75pt; padding-left:5.4pt; padding-right:5.03pt; vertical-align:middle; width:27.2pt"><p style="line-height:12pt; margin:0pt; text-align:center"><span style="font-family:宋体; font-size:9pt">联系</span><br /><span style="font-family:宋体; font-size:9pt">电话</span></p></td>
       <td colspan="4" style="border-bottom-color:#000000; border-bottom-style:solid; border-bottom-width:0.75pt; border-right-color:#000000; border-right-style:solid; border-right-width:0.75pt; border-top-color:#000000; border-top-style:solid; border-top-width:0.75pt; padding-left:5.4pt; padding-right:5.03pt; vertical-align:middle; width:118.2pt"><p style="line-height:12pt; margin:0pt; text-align:center"><span style="font-family:宋体; font-size:9pt">张三丰</span></p></td>
       <td style="border-bottom-color:#000000; border-bottom-style:solid; border-bottom-width:0.75pt; border-right-color:#000000; border-right-style:solid; border-right-width:0.75pt; padding-left:5.4pt; padding-right:5.03pt; vertical-align:middle; width:48.45pt"><p style="line-height:12pt; margin:0pt; text-align:center"><span style="font-family:宋体; font-size:9pt">家属住址</span><br /><span style="font-family:宋体; font-size:9pt">或工作单位</span></p></td>
       <td colspan="2" style="border-bottom-color:#000000; border-bottom-style:solid; border-bottom-width:0.75pt; border-right-color:#000000; border-right-style:solid; border-right-width:0.75pt; border-top-color:#000000; border-top-style:solid; border-top-width:0.75pt; padding-left:5.4pt; padding-right:5.03pt; vertical-align:middle; width:120.6pt"><p style="line-height:12pt; margin:0pt; text-align:center"><span style="font-family:宋体; font-size:9pt">张三丰</span></p></td>
      </tr>
      <tr style="height:26.1pt">
       <td colspan="3" style="border-bottom-color:#000000; border-bottom-style:solid; border-bottom-width:0.75pt; border-left-color:#000000; border-left-style:solid; border-left-width:0.75pt; border-right-color:#000000; border-right-style:solid; border-right-width:0.75pt; border-top-color:#000000; border-top-style:solid; border-top-width:0.75pt; padding-left:5.03pt; padding-right:5.03pt; vertical-align:middle; width:153.45pt"><p style="line-height:12pt; margin:0pt"><span style="font-family:宋体; font-size:9pt"> 致死的主要疾病诊断</span></p></td>
       <td colspan="6" style="border-bottom-color:#000000; border-bottom-style:solid; border-bottom-width:0.75pt; border-right-color:#000000; border-right-style:solid; border-right-width:0.75pt; border-top-color:#000000; border-top-style:solid; border-top-width:0.75pt; padding-left:5.4pt; padding-right:5.03pt; vertical-align:middle; width:215.45pt"><p style="line-height:12pt; margin:0pt; text-align:center"><span style="font-family:宋体; font-size:9pt">疾病名称（</span><span style="font-family:宋体; font-size:9pt">勿填症状</span><span style="font-family:宋体; font-size:9pt">体征）</span></p></td>
       <td colspan="2" style="border-bottom-color:#000000; border-bottom-style:solid; border-bottom-width:0.75pt; border-right-color:#000000; border-right-style:solid; border-right-width:0.75pt; border-top-color:#000000; border-top-style:solid; border-top-width:0.75pt; padding-left:5.4pt; padding-right:5.03pt; vertical-align:middle; width:120.6pt"><p style="line-height:12pt; margin:0pt; text-align:center"><span style="font-family:宋体; font-size:9pt">发病至死亡大概间隔时间</span></p></td>
      </tr>
      <tr style="height:26.1pt">
       <td colspan="3" style="border-bottom-color:#000000; border-bottom-style:solid; border-bottom-width:0.75pt; border-left-color:#000000; border-left-style:solid; border-left-width:0.75pt; border-right-color:#000000; border-right-style:solid; border-right-width:0.75pt; border-top-color:#000000; border-top-style:solid; border-top-width:0.75pt; padding-left:5.03pt; padding-right:5.03pt; vertical-align:middle; width:153.45pt"><p style="line-height:12pt; margin:0pt"><span style="font-family:宋体; font-size:9pt"> </span><span style="font-family:宋体; font-size:9pt">I.</span><span style="font-family:宋体; font-size:9pt">(a)直接死亡原因</span></p></td>
       <td colspan="6" style="border-bottom-color:#000000; border-bottom-style:solid; border-bottom-width:0.75pt; border-right-color:#000000; border-right-style:solid; border-right-width:0.75pt; border-top-color:#000000; border-top-style:solid; border-top-width:0.75pt; padding-left:5.4pt; padding-right:5.03pt; vertical-align:middle; width:215.45pt"><p style="line-height:12pt; margin:0pt; text-align:center"><span style="font-family:宋体; font-size:9pt">张三丰</span></p></td>
       <td colspan="2" style="border-bottom-color:#000000; border-bottom-style:solid; border-bottom-width:0.75pt; border-right-color:#000000; border-right-style:solid; border-right-width:0.75pt; border-top-color:#000000; border-top-style:solid; border-top-width:0.75pt; padding-left:5.4pt; padding-right:5.03pt; vertical-align:middle; width:120.6pt"><p style="line-height:12pt; margin:0pt; text-align:center"><span style="font-family:宋体; font-size:9pt">张三丰</span></p></td>
      </tr>
      <tr style="height:26.1pt">
       <td colspan="3" style="border-bottom-color:#000000; border-bottom-style:solid; border-bottom-width:0.75pt; border-left-color:#000000; border-left-style:solid; border-left-width:0.75pt; border-right-color:#000000; border-right-style:solid; border-right-width:0.75pt; border-top-color:#000000; border-top-style:solid; border-top-width:0.75pt; padding-left:5.03pt; padding-right:5.03pt; vertical-align:middle; width:153.45pt"><p style="line-height:12pt; margin:0pt"><span style="font-family:宋体; font-size:9pt"> (b)引起(a)的疾病或情况</span></p></td>
       <td colspan="6" style="border-bottom-color:#000000; border-bottom-style:solid; border-bottom-width:0.75pt; border-right-color:#000000; border-right-style:solid; border-right-width:0.75pt; border-top-color:#000000; border-top-style:solid; border-top-width:0.75pt; padding-left:5.4pt; padding-right:5.03pt; vertical-align:middle; width:215.45pt"><p style="line-height:12pt; margin:0pt; text-align:center"><span style="font-family:宋体; font-size:9pt">张三丰</span></p></td>
       <td colspan="2" style="border-bottom-color:#000000; border-bottom-style:solid; border-bottom-width:0.75pt; border-right-color:#000000; border-right-style:solid; border-right-width:0.75pt; border-top-color:#000000; border-top-style:solid; border-top-width:0.75pt; padding-left:5.4pt; padding-right:5.03pt; vertical-align:middle; width:120.6pt"><p style="line-height:12pt; margin:0pt; text-align:center"><span style="font-family:宋体; font-size:9pt">张三丰</span></p></td>
      </tr>
      <tr style="height:26.1pt">
       <td colspan="3" style="border-bottom-color:#000000; border-bottom-style:solid; border-bottom-width:0.75pt; border-left-color:#000000; border-left-style:solid; border-left-width:0.75pt; border-right-color:#000000; border-right-style:solid; border-right-width:0.75pt; border-top-color:#000000; border-top-style:solid; border-top-width:0.75pt; padding-left:5.03pt; padding-right:5.03pt; vertical-align:middle; width:153.45pt"><p style="line-height:12pt; margin:0pt"><span style="font-family:宋体; font-size:9pt"> (c)引起(b)的疾病或情况</span></p></td>
       <td colspan="6" style="border-bottom-color:#000000; border-bottom-style:solid; border-bottom-width:0.75pt; border-right-color:#000000; border-right-style:solid; border-right-width:0.75pt; border-top-color:#000000; border-top-style:solid; border-top-width:0.75pt; padding-left:5.4pt; padding-right:5.03pt; vertical-align:middle; width:215.45pt"><p style="line-height:12pt; margin:0pt; text-align:center"><span style="font-family:宋体; font-size:9pt">张三丰</span></p></td>
       <td colspan="2" style="border-bottom-color:#000000; border-bottom-style:solid; border-bottom-width:0.75pt; border-right-color:#000000; border-right-style:solid; border-right-width:0.75pt; border-top-color:#000000; border-top-style:solid; border-top-width:0.75pt; padding-left:5.4pt; padding-right:5.03pt; vertical-align:middle; width:120.6pt"><p style="line-height:12pt; margin:0pt; text-align:center"><span style="font-family:宋体; font-size:9pt">张三丰</span></p></td>
      </tr>
      <tr style="height:26.1pt">
       <td colspan="3" style="border-bottom-color:#000000; border-bottom-style:solid; border-bottom-width:0.75pt; border-left-color:#000000; border-left-style:solid; border-left-width:0.75pt; border-right-color:#000000; border-right-style:solid; border-right-width:0.75pt; border-top-color:#000000; border-top-style:solid; border-top-width:0.75pt; padding-left:5.03pt; padding-right:5.03pt; vertical-align:middle; width:153.45pt"><p style="line-height:12pt; margin:0pt"><span style="font-family:宋体; font-size:9pt"> (d)引起(c)的疾病或情况</span></p></td>
       <td colspan="6" style="border-bottom-color:#000000; border-bottom-style:solid; border-bottom-width:0.75pt; border-right-color:#000000; border-right-style:solid; border-right-width:0.75pt; border-top-color:#000000; border-top-style:solid; border-top-width:0.75pt; padding-left:5.4pt; padding-right:5.03pt; vertical-align:middle; width:215.45pt"><p style="line-height:12pt; margin:0pt; text-align:center"><span style="font-family:宋体; font-size:9pt">张三丰</span></p></td>
       <td colspan="2" style="border-bottom-color:#000000; border-bottom-style:solid; border-bottom-width:0.75pt; border-right-color:#000000; border-right-style:solid; border-right-width:0.75pt; border-top-color:#000000; border-top-style:solid; border-top-width:0.75pt; padding-left:5.4pt; padding-right:5.03pt; vertical-align:middle; width:120.6pt"><p style="line-height:12pt; margin:0pt; text-align:center"><span style="font-family:宋体; font-size:9pt">张三丰</span></p></td>
      </tr>
      <tr style="height:28.5pt">
       <td colspan="3" style="border-bottom-color:#000000; border-bottom-style:solid; border-bottom-width:0.75pt; border-left-color:#000000; border-left-style:solid; border-left-width:0.75pt; border-right-color:#000000; border-right-style:solid; border-right-width:0.75pt; border-top-color:#000000; border-top-style:solid; border-top-width:0.75pt; padding-left:5.03pt; padding-right:5.03pt; vertical-align:middle; width:153.45pt"><p style="line-height:12pt; margin:0pt"><span style="font-family:宋体; font-size:9pt"> II.其他疾病诊断（促进死亡，但与</span><br /><span style="font-family:宋体; font-size:9pt"> 导致死亡无关的其他重要情况）</span></p></td>
       <td colspan="6" style="border-bottom-color:#000000; border-bottom-style:solid; border-bottom-width:0.75pt; border-right-color:#000000; border-right-style:solid; border-right-width:0.75pt; border-top-color:#000000; border-top-style:solid; border-top-width:0.75pt; padding-left:5.4pt; padding-right:5.03pt; vertical-align:middle; width:215.45pt"><p style="line-height:12pt; margin:0pt; text-align:center"><span style="font-family:宋体; font-size:9pt">张三丰</span></p></td>
       <td colspan="2" style="border-bottom-color:#000000; border-bottom-style:solid; border-bottom-width:0.75pt; border-left-color:#000000; border-left-style:solid; border-left-width:0.75pt; border-right-color:#000000; border-right-style:solid; border-right-width:0.75pt; border-top-color:#000000; border-top-style:solid; border-top-width:0.75pt; padding-left:5.03pt; padding-right:5.03pt; vertical-align:middle; width:120.6pt"><p style="line-height:12pt; margin:0pt; text-align:center"><span style="font-family:宋体; font-size:9pt">张三丰</span></p></td>
      </tr>
      <tr style="height:27.95pt">
       <td style="border-bottom-color:#000000; border-bottom-style:solid; border-bottom-width:0.75pt; border-left-color:#000000; border-left-style:solid; border-left-width:0.75pt; border-right-color:#000000; border-right-style:solid; border-right-width:0.75pt; padding-left:5.03pt; padding-right:5.03pt; vertical-align:middle; width:48.2pt"><p style="line-height:12pt; margin:0pt; text-align:center"><span style="font-family:宋体; font-size:6pt">生前主要疾病</span><br /><span style="font-family:宋体; font-size:6pt">最高诊断单位</span></p></td>
       <td colspan="7" style="border-bottom-color:#000000; border-bottom-style:solid; border-bottom-width:0.75pt; border-right-color:#000000; border-right-style:solid; border-right-width:0.75pt; border-top-color:#000000; border-top-style:solid; border-top-width:0.75pt; padding-left:5.4pt; padding-right:5.03pt; vertical-align:middle; width:261.45pt"><p style="line-height:12pt; margin:0pt; text-align:center"><span style="font-family:宋体; font-size:9pt">张三丰</span></p></td>
       <td style="border-bottom-color:#000000; border-bottom-style:solid; border-bottom-width:0.75pt; padding-left:5.4pt; padding-right:5.4pt; vertical-align:middle; width:48.45pt"><p style="line-height:12pt; margin:0pt; text-align:center"><span style="font-family:宋体; font-size:6pt">生前主要疾病</span><br /><span style="font-family:宋体; font-size:6pt">最高诊断依据</span></p></td>
       <td colspan="2" style="border-bottom-color:#000000; border-bottom-style:solid; border-bottom-width:0.75pt; border-left-color:#000000; border-left-style:solid; border-left-width:0.75pt; border-right-color:#000000; border-right-style:solid; border-right-width:0.75pt; border-top-color:#000000; border-top-style:solid; border-top-width:0.75pt; padding-left:5.03pt; padding-right:5.03pt; vertical-align:middle; width:120.6pt"><p style="line-height:12pt; margin:0pt; text-align:center"><span style="font-family:宋体; font-size:9pt">张三丰</span></p></td>
      </tr>
      <tr style="height:28.5pt">
       <td style="border-left-color:#000000; border-left-style:solid; border-left-width:0.75pt; border-right-color:#000000; border-right-style:solid; border-right-width:0.75pt; padding-left:5.03pt; padding-right:5.03pt; vertical-align:middle; width:48.2pt"><p style="line-height:12pt; margin:0pt; text-align:center"><span style="font-family:宋体; font-size:9pt">医师签名</span></p></td>
       <td colspan="2" style="border-right-color:#000000; border-right-style:solid; border-right-width:0.75pt; border-top-color:#000000; border-top-style:solid; border-top-width:0.75pt; padding-left:5.4pt; padding-right:5.03pt; vertical-align:middle; width:94.45pt"><p style="line-height:12pt; margin:0pt; text-align:center"><span style="font-family:宋体; font-size:9pt">张三丰</span></p></td>
       <td colspan="5" style="border-left-color:#000000; border-left-style:solid; border-left-width:0.75pt; border-top-color:#000000; border-top-style:solid; border-top-width:0.75pt; padding-left:5.03pt; padding-right:5.4pt; vertical-align:middle; width:156.2pt"><p style="line-height:12pt; margin:0pt"><span style="font-family:宋体; font-size:9pt"> 医疗卫生</span><br /><span style="font-family:宋体; font-size:9pt"> 机构盖章</span></p></td>
       <td style="border-left-color:#000000; border-left-style:solid; border-left-width:0.75pt; border-right-color:#000000; border-right-style:solid; border-right-width:0.75pt; border-top-color:#000000; border-top-style:solid; border-top-width:0.75pt; padding-left:5.03pt; padding-right:5.03pt; vertical-align:middle; width:48.45pt"><p style="line-height:12pt; margin:0pt"><span style="font-family:宋体; font-size:9pt"> 填表日期：</span></p></td>
       <td colspan="2" style="border-left-color:#000000; border-left-style:solid; border-left-width:0.75pt; border-right-color:#000000; border-right-style:solid; border-right-width:0.75pt; border-top-color:#000000; border-top-style:solid; border-top-width:0.75pt; padding-left:5.03pt; padding-right:5.03pt; vertical-align:middle; width:120.6pt"><p style="line-height:12pt; margin:0pt 0pt 0pt 17.1pt; orphans:0; text-align:center; widows:0"><span style="font-family:宋体; font-size:9pt">张三丰</span></p></td>
      </tr>
      <tr style="height:28.5pt">
       <td colspan="3" style="border-bottom-color:#000000; border-bottom-style:solid; border-bottom-width:0.75pt; border-left-color:#000000; border-left-style:solid; border-left-width:0.75pt; border-right-color:#000000; border-right-style:solid; border-right-width:0.75pt; border-top-color:#000000; border-top-style:solid; border-top-width:0.75pt; padding-left:5.03pt; padding-right:5.03pt; vertical-align:middle; width:153.45pt"><p style="line-height:14pt; margin:0pt"><span style="font-family:宋体; font-size:9pt">(以下由编码人员填写) 根本死亡原因:</span></p></td>
       <td colspan="5" style="border-bottom-color:#000000; border-bottom-style:solid; border-bottom-width:0.75pt; border-left-color:#000000; border-left-style:solid; border-left-width:0.75pt; border-right-color:#000000; border-right-style:solid; border-right-width:0.75pt; border-top-color:#000000; border-top-style:solid; border-top-width:0.75pt; padding-left:5.03pt; padding-right:5.03pt; vertical-align:middle; width:156.2pt"><p style="line-height:14pt; margin:0pt; orphans:0; text-align:center; widows:0"><span style="font-family:宋体; font-size:9pt">张三丰</span></p></td>
       <td style="border-bottom-color:#000000; border-bottom-style:solid; border-bottom-width:0.75pt; border-right-color:#000000; border-right-style:solid; border-right-width:0.75pt; border-top-color:#000000; border-top-style:solid; border-top-width:0.75pt; padding-left:5.4pt; padding-right:5.03pt; vertical-align:middle; width:48.45pt"><p style="line-height:14pt; margin:0pt"><span style="font-family:宋体; font-size:9pt"> ICD编码：</span></p></td>
       <td colspan="2" style="border-bottom-color:#000000; border-bottom-style:solid; border-bottom-width:0.75pt; border-left-color:#000000; border-left-style:solid; border-left-width:0.75pt; border-right-color:#000000; border-right-style:solid; border-right-width:0.75pt; border-top-color:#000000; border-top-style:solid; border-top-width:0.75pt; padding-left:5.03pt; padding-right:5.03pt; vertical-align:middle; width:120.6pt"><p style="line-height:14pt; margin:0pt; text-align:center"><span style="font-family:宋体; font-size:9pt">张三丰</span></p></td>
      </tr>
      <tr style="height:23.25pt">
       <td colspan="11" style="border-bottom-color:#000000; border-bottom-style:solid; border-bottom-width:0.75pt; padding-left:5.4pt; padding-right:5.4pt; vertical-align:bottom; width:511.1pt"><p style="line-height:14pt; margin:0pt; text-align:center"><span style="font-family:宋体; font-size:15pt; font-weight:bold"> </span><span style="font-family:宋体; font-size:15pt; font-weight:bold">死亡调查记录</span></p></td>
      </tr>
      <tr style="height:15.6pt">
       <td colspan="11" rowspan="6" style="border-bottom-color:#000000; border-bottom-style:solid; border-bottom-width:0.75pt; border-left-color:#000000; border-left-style:solid; border-left-width:0.75pt; border-right-color:#000000; border-right-style:solid; border-right-width:0.75pt; border-top-color:#000000; border-top-style:solid; border-top-width:0.75pt; padding-left:5.03pt; padding-right:5.03pt; vertical-align:top; width:511.1pt"><p style="line-height:11pt; margin:0pt"><span style="font-family:宋体; font-size:9pt">张三丰</span></p></td>
      </tr>
      <tr style="height:15.6pt">
       <td style="border:none; height:15.6pt; width:0pt"></td>
      </tr>
      <tr style="height:15.6pt">
       <td style="border:none; height:15.6pt; width:0pt"></td>
      </tr>
      <tr style="height:15.6pt">
       <td style="border:none; height:15.6pt; width:0pt"></td>
      </tr>
      <tr style="height:15.6pt">
       <td style="border:none; height:15.6pt; width:0pt"></td>
      </tr>
      <tr style="height:11pt">
       <td style="border:none; height:11pt; width:0pt"></td>
      </tr>
      <tr style="height:26.1pt">
       <td style="border-bottom-color:#000000; border-bottom-style:solid; border-bottom-width:0.75pt; border-left-color:#000000; border-left-style:solid; border-left-width:0.75pt; border-right-color:#000000; border-right-style:solid; border-right-width:0.75pt; padding-left:5.03pt; padding-right:5.03pt; vertical-align:middle; width:48.2pt"><p style="line-height:11pt; margin:0pt; text-align:center"><span style="font-family:宋体; font-size:9pt">被调查者</span><br /><span style="font-family:宋体; font-size:9pt">姓 名</span></p></td>
       <td style="border-bottom-color:#000000; border-bottom-style:solid; border-bottom-width:0.75pt; padding-left:5.4pt; padding-right:5.4pt; vertical-align:middle; width:53.2pt"><p style="line-height:11pt; margin:0pt; text-align:center"><span style="font-family:宋体; font-size:9pt">张三丰</span></p></td>
       <td style="border-bottom-color:#000000; border-bottom-style:solid; border-bottom-width:0.75pt; border-left-color:#000000; border-left-style:solid; border-left-width:0.75pt; border-right-color:#000000; border-right-style:solid; border-right-width:0.75pt; padding-left:5.03pt; padding-right:5.03pt; vertical-align:middle; width:30.45pt"><p style="line-height:11pt; margin:0pt; text-align:center"><span style="font-family:宋体; font-size:9pt">与死者</span><br /><span style="font-family:宋体; font-size:9pt">关 系</span></p></td>
       <td style="border-bottom-color:#000000; border-bottom-style:solid; border-bottom-width:0.75pt; border-right-color:#000000; border-right-style:solid; border-right-width:0.75pt; padding-left:5.4pt; padding-right:5.03pt; vertical-align:middle; width:27.2pt"><p style="line-height:11pt; margin:0pt; text-align:center"><span style="font-family:宋体; font-size:9pt">张三丰</span></p></td>
       <td colspan="2" style="border-bottom-color:#000000; border-bottom-style:solid; border-bottom-width:0.75pt; border-right-color:#000000; border-right-style:solid; border-right-width:0.75pt; padding-left:5.4pt; padding-right:5.03pt; vertical-align:middle; width:47.2pt"><p style="line-height:11pt; margin:0pt; text-align:center"><span style="font-family:宋体; font-size:9pt">联系</span><br /><span style="font-family:宋体; font-size:9pt">电话</span></p></td>
       <td colspan="2" style="border-bottom-color:#000000; border-bottom-style:solid; border-bottom-width:0.75pt; border-right-color:#000000; border-right-style:solid; border-right-width:0.75pt; border-top-color:#000000; border-top-style:solid; border-top-width:0.75pt; padding-left:5.4pt; padding-right:5.03pt; vertical-align:middle; width:60.2pt"><p style="line-height:11pt; margin:0pt; text-align:center"><span style="font-family:宋体; font-size:9pt">张三丰</span></p></td>
       <td style="border-bottom-color:#000000; border-bottom-style:solid; border-bottom-width:0.75pt; border-right-color:#000000; border-right-style:solid; border-right-width:0.75pt; padding-left:5.4pt; padding-right:5.03pt; vertical-align:middle; width:48.45pt"><p style="line-height:11pt; margin:0pt; text-align:center"><span style="font-family:宋体; font-size:9pt">联系地址</span><br /><span style="font-family:宋体; font-size:9pt">或工作单位</span></p></td>
       <td colspan="2" style="border-bottom-color:#000000; border-bottom-style:solid; border-bottom-width:0.75pt; border-right-color:#000000; border-right-style:solid; border-right-width:0.75pt; border-top-color:#000000; border-top-style:solid; border-top-width:0.75pt; padding-left:5.4pt; padding-right:5.03pt; vertical-align:middle; width:120.6pt"><p style="line-height:11pt; margin:0pt; text-align:center"><span style="font-family:宋体; font-size:9pt">张三丰</span></p></td>
      </tr>
      <tr style="height:14.9pt">
       <td style="border-bottom-color:#000000; border-bottom-style:solid; border-bottom-width:0.75pt; border-left-color:#000000; border-left-style:solid; border-left-width:0.75pt; border-right-color:#000000; border-right-style:solid; border-right-width:0.75pt; padding-left:5.03pt; padding-right:5.03pt; vertical-align:middle; width:48.2pt"><p style="line-height:11pt; margin:0pt; text-align:center"><span style="font-family:宋体; font-size:9pt">死因推断</span></p></td>
       <td colspan="3" style="border-bottom-color:#000000; border-bottom-style:solid; border-bottom-width:0.75pt; border-right-color:#000000; border-right-style:solid; border-right-width:0.75pt; border-top-color:#000000; border-top-style:solid; border-top-width:0.75pt; padding-left:5.4pt; padding-right:5.03pt; vertical-align:middle; width:132.45pt"><p style="line-height:11pt; margin:0pt; text-align:center"><span style="font-family:宋体; font-size:9pt">张三丰</span></p></td>
       <td colspan="2" style="border-bottom-color:#000000; border-bottom-style:solid; border-bottom-width:0.75pt; border-right-color:#000000; border-right-style:solid; border-right-width:0.75pt; padding-left:5.4pt; padding-right:5.03pt; vertical-align:middle; width:47.2pt"><p style="line-height:11pt; margin:0pt; text-align:center"><span style="font-family:宋体; font-size:9pt">调查者签名</span></p></td>
       <td colspan="2" style="border-bottom-color:#000000; border-bottom-style:solid; border-bottom-width:0.75pt; border-top-color:#000000; border-top-style:solid; border-top-width:0.75pt; padding-left:5.4pt; padding-right:5.4pt; vertical-align:middle; width:60.2pt"><p style="line-height:11pt; margin:0pt; text-align:center"><span style="font-family:宋体; font-size:9pt">张三丰</span></p></td>
       <td style="border-bottom-color:#000000; border-bottom-style:solid; border-bottom-width:0.75pt; border-left-color:#000000; border-left-style:solid; border-left-width:0.75pt; border-right-color:#000000; border-right-style:solid; border-right-width:0.75pt; padding-left:5.03pt; padding-right:5.03pt; vertical-align:middle; width:48.45pt"><p style="line-height:11pt; margin:0pt; text-align:center"><span style="font-family:宋体; font-size:9pt">调查日期</span></p></td>
       <td colspan="2" style="border-bottom-color:#000000; border-bottom-style:solid; border-bottom-width:0.75pt; border-right-color:#000000; border-right-style:solid; border-right-width:0.75pt; border-top-color:#000000; border-top-style:solid; border-top-width:0.75pt; padding-left:5.4pt; padding-right:5.03pt; vertical-align:middle; width:120.6pt"><p style="line-height:11pt; margin:0pt; text-align:center"><span style="font-family:宋体; font-size:9pt">张三丰</span></p></td>
      </tr>
      <tr style="height:25.5pt">
       <td colspan="11" style="border-top-color:#000000; border-top-style:solid; border-top-width:0.75pt; padding-left:5.4pt; padding-right:5.4pt; vertical-align:middle; width:511.1pt"><p style="line-height:11pt; margin:0pt"><span style="font-family:宋体; font-size:8.5pt"> 注：①此表填写范围为在家、养老服务机构、其他场所正常死亡者；②被调查者应为死者近亲或知情人；③调查时应出具以下资料：被调查者有效身份证件，居住地居委会或村委会证明，死者身份证和/或户口簿、生前病史卡.</span></p></td>
      </tr>
     </tbody>
    </table>

</body>
</html>
'''
